apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gym-portal
labels:
  - pairs:
      app.kubernetes.io/part-of: gym-portal
resources:
  - namespace.yaml
  - configmap.yaml
  - mysql.yaml
  - backend.yaml
  - frontend.yaml
